# Generated by Django 3.0.8 on 2020-07-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
